blank_issues_enabled: false
contact_links:
  - name: Contribution policy
    url: https://github.com/Prism-Reporting/reporting/blob/main/CONTRIBUTING.md
    about: The project is not accepting external pull requests right now. Please open an issue instead.
